on:
  push:
    paths:
      - 'configurations/**.json'
    branches:
      - main
    

jobs:
  syncconfig:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}