on:
  push:
    branches:
      - main
    

jobs:
  syncconfig:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az appconfig kv export -n ez-app-config -d file --path remote.json --format json --yes

    - name: Compare File
      run: |
        pwd
        ls -la
        diff --help
        jq --help
        
