on:
  push:
    branches:
      - main
    

jobs:
  syncconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az appconfig kv export -n ez-app-config -d file --path remote.json --format json --yes

    - name: Compare File
      run: |
        pwd
        ls -la
        jq -S . remote.json > remote_sorted.json
        jq -S . configurations/config.json > config.sorted.json
        diff --side-by-side remote_sorted.json config.sorted.json && echo "no difference" || echo "differences!"

  applyConfig:
    runs-on: ubuntu-latest
    environment: test
    needs: syncconfig
    steps: 
    - uses: actions/checkout@v4
    
    - name: Azure Login action
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az appconfig kv import -n ez-app-config -s file --path configurations/config.json --format json --yes
      

